### PR TITLE
Change label of 'Minimal Server Selection' to 'Minimal Base System' (…

### PR DESCRIPTION
**Pull request by DimStar77**
…boo#962725).

@lnussel Can you please give your +1 / -1 here too?

### CODE REVIEW

**Comment by lnussel** [comment]
I'd just remove this option.

**Comment by DimStar77** [comment]
this is the one option we test in openQA as 'textmode'

**Comment by lnussel** [comment]
yes, that has to be fixed :smile:

**Comment by lnussel** [comment]
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1765

**Comment by DimStar77** [comment]
ok then - current PR removes that entry completely from the control.xml

a submission to openSUSE:Factory/patterns-openSUSE is pending to get generic_server on the DVD and the openQA test is also queued up (should be merged after we get the pattern change in)

**Comment by imobachgs** [comment]
LGTM

**Pull request merged**
