### PR TITLE
Add btrfs_default_subvolume

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by mvidner** [comment]
Thank you Ludwig!
The commit messages should be copied to package/*.changes. Also, the version should be increased -- that way [a Jenkins job](https://ci.opensuse.org/view/Yast/job/yast-skelcd-control-openSUSE-master/) will automatically submit the package to OBS.

Someone more knowledgeable than me should comment on the actual `<partitioning>` changes.

**Comment by lnussel** [comment]
note that CONTRIBUTING.md explicity says to not touch version and changes

**Comment by lnussel** [comment]
o_O

**Comment by jreidinger** [comment]
thanks

**Pull request merged**
