### PR TITLE
adjust subvolume list to have NoCOW /var instead of many subvolumes

### PR DESCRIPTION
**Pull request by sysrich**
Also includes free trailing whitespace tidyup - you're welcome ;)

### CODE REVIEW

**Comment by mvidner** [comment]
Thanks! I don't really understand this :-) so pinged the storage people.
- is there a a Bugzilla / Fate / mailing list reference for this? I love tracking IDs!
- the commit message describes *what* is being done. can we also describe *why* it's being done?

**Comment by ancorgs** [comment]
As @mvidner said. I'm alway VERY happy to reduce the number of subvolumes, but we will need a pointer to the fate/bugzilla/mailing list discussion/whatsnot. If there is none, please just explain the rationale somehow (directly in the changelog entry is fine).

Sorry if it's sound too defensive, but we must save some time for future code archaeologists (i.e. our "future us"). :-)

**Comment by thkukuk** [comment]
It's openSUSE, we don't use FATE there. One announcement can be found here:
https://lists.opensuse.org/opensuse-packaging/2017-11/msg00017.html

**Comment by ancorgs** [comment]
Cool. Adding that link as a comment right before the definition of the var subvolume should address everybody's concerns.

**Comment by sysrich** [comment]
Ping - PR updated with requested comment, please re-review

**Pull request merged**
