### PR TITLE
 Add 'fcoe-client' to the list of clonable modules

### PR DESCRIPTION
**Pull request by teclator**
- https://trello.com/c/eLMiRWmH/1350-2-bug-1078991-l3-autoyast-unable-to-find-disk-with-option-withfcoe

### CODE REVIEW

**Comment by jreidinger** [comment]
it failed because it looks like travis is missing xmllint

**Comment by jreidinger** [comment]
otherwise looks good.

**Comment by teclator** [comment]
I would ignore the travis error, or we could use the Dockerfile from openSUSE-Leap42_3

**Comment by jreidinger** [comment]
well, problem with this is that new skelcd would be never used, so not much affect this will have

**Comment by teclator** [comment]
@jreidinger yep, so what to do then?

**Comment by jreidinger** [comment]
@teclator I would fix only leap 15 and TW

**Pull request closed without merging**
