### PR TITLE
Fix boo#1182915 - add repo-debug-update to Leap 15.3

### PR DESCRIPTION
**Pull request by lkocman**
* supply update-debug repository

Note for the pull request authors:

The `master` branch is intended for the openSUSE Tumbleweed only,
if you want to have the same change in the openSUSE Leap then backport
it to the respective `openSUSE-X_Y` branch.

### CODE REVIEW

**Comment by lkocman** [comment]
I did receive green from Max on the SR. Yast team could you please merge it (also wrote on irc).

**Comment by teclator** [comment]
I miss the version bump and changelog entry referencing the bug (https://bugzilla.suse.com/show_bug.cgi?id=1182915)

**Comment by teclator** [comment]
https://github.com/yast/skelcd-control-openSUSE/blob/openSUSE-15_3/package/skelcd-control-openSUSE.changes#L1

> Fixed @teclator

The changelog entry is still pending, I will merge this PR and add it myself.

**Review by teclator — APPROVED** [review]
LGTM

**Pull request merged**
