### PR TITLE
Add missing slash to debug/update/leap/42.2/oss

### PR DESCRIPTION
**Pull request by lnussel**
For consistency with other entries (boo#997232)

### CODE REVIEW

**Comment by imobachgs** [comment]
LGTM. Just curiosity, would be self-update available in Leap 42.2?

**Comment by lnussel** [comment]
No, after discussion with SLE release management and maintenance I decided not to enable it for Leap. YaST on Leap is expected to be bug free :smile:

**Comment by lnussel** [comment]
so will this be merged and submitted for Beta3?

**Comment by imobachgs** [comment]
Sorry, I forgot your last comment (and I though you had permissions to merge it).

**Pull request merged**
