### PR TITLE
Updating to TW from Leap 42.1 should be considered supported

### PR DESCRIPTION
**Pull request by DimStar77**

### CODE REVIEW

**Comment by DimStar77** [comment]
Currently openQA reports https://openqa.opensuse.org/tests/111622/modules/upgrade_select/steps/9

**Comment by jreidinger** [comment]
LGTM, do you have rights to merge it?

**Comment by DimStar77** [comment]
No merge rights from my end - no.

**Comment by jreidinger** [comment]
ok, so I merge it myself. Thanks for fix

**Pull request merged**
