### PR TITLE
Fix repo URL for s390x

### PR DESCRIPTION
**Pull request by binary-sequence**
At the moment the repositories added are for x86_64.

### CODE REVIEW

**Comment by jreidinger** [comment]
it looks reasonable for me, I am just missing version bumb

**Comment by jreidinger** [comment]
just make it ready for review and I can merge it.

**Comment by binary-sequence** [comment]
I would like to verify first that those are the right repositories.
Because I get 404. But, I also get 404 with aarch64 repos.
I don't understand how this is supposed to work.

**Comment by jreidinger** [comment]
for me links work http://download.opensuse.org/ports/ . It is just sed, so remaining part like iso or repo is kept. I merged it, thanks for patch.

**Pull request merged**
