### PR TITLE
enable firewall by default in server install profiles

### PR DESCRIPTION
**Pull request by jsegitz**

### CODE REVIEW

**Comment by sysrich** [comment]
This change will only impact Tumbleweed- please also submit desired changes to the right branch for 15.1

**Comment by sysrich** [comment]
You also need to update the .spec file and the changes appropriately, or else this PR can’t be merged and submitted via the Yast teams CI

**Comment by jsegitz** [comment]
thank you for the hints @sysrich

**Comment by sysrich** [comment]
@jsegitz you're welcome.. +1 from me - I'll ping the YaST team in a bit so they can be sure to review and merge it :)

**Pull request merged**
