### PR TITLE
Use lightdm as displaymanager when installing LXDE

### PR DESCRIPTION
**Pull request by DimStar77**
See conversation at
https://lists.opensuse.org/opensuse-factory/2016-07/msg00417.html

### CODE REVIEW

**Comment by jreidinger** [comment]
LGTM, do you have permissions to merge?

**Comment by jreidinger** [comment]
and btw if you want to release it, then please also increase version, otherwise it will be submitted only together with next version bump

**Comment by DimStar77** [comment]
No permissions for me in the yast repo

**Comment by DimStar77** [comment]
oh.. finding the version.... one second then before merging

**Comment by jreidinger** [comment]
thanks, merging

**Pull request merged**
