### PR TITLE
/var/lib/ceph as btrfs subvolume with CoW disabled (bsc#1013011)

### PR DESCRIPTION
**Pull request by kmroz**
Signed-off-by: Karol Mroz <kmroz@suse.de>

### CODE REVIEW

**Comment by jreidinger** [comment]
it looks fine, but it should contain version increase and changes entry including bugzilla number for reference.

**Comment by kmroz** [comment]
@jreidinger - Thank you.  PR updated!

**Comment by jreidinger** [comment]
good, just there is a conflict now. Can you please solve it? I will merge it afterward ( better ping me ). thanks

**Comment by kmroz** [comment]
@jreidinger - Rebased and conflict resolved.

**Comment by kmroz** [comment]
@jreidinger - ping... PR should be ready.

**Comment by jreidinger** [comment]
it is already superseeded with own /var subvolume in https://github.com/yast/skelcd-control-openSUSE/pull/102

**Pull request closed without merging**
