### PR TITLE
Replace the generic_server pattern reference with console.

### PR DESCRIPTION
**Pull request by simotek**
As part of the patterns cleanup the generic_server pattern was merged into the console pattern and removed.

### CODE REVIEW

**Comment by simotek** [comment]
Not sure how this change would cause Travis to fail.

**Comment by lslezak** [comment]
BTW the desktop selection dialog still uses the [Server (Text Mode)](https://github.com/yast/skelcd-control-openSUSE/blob/master/control/control.openSUSE.xml#L476) label and the [description](https://github.com/yast/skelcd-control-openSUSE/blob/master/control/control.openSUSE.xml#L518) as well.

Should we change that to `Console` (or something like that) or is the `Server` term still OK?

**Comment by simotek** [comment]
Text mode implies server I guess, the old server pattern just installed a few console tools and there was quite some overlap which is why they were merged.

I'm open to it changing at some point, particularly removing the quotes there but that will generate lots of mailing list discussion so we should leave it as is for now as its what was agreed to in the last round of desktop selection discussions.

**Comment by lslezak** [comment]
OK, so lets keep that `Server` label for now.

**Pull request merged**
