### PR TITLE
Adjust for 42.2

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by lnussel** [comment]
Note: please don't merge into master! create a branch for 42.2 instead!

**Comment by lnussel** [comment]
any news?

**Comment by jreidinger** [comment]
@lnussel thanks for patch. Do you want to base 42.2 on master or on 42.1? Then I will create proper branch and cherry pick your commits

**Comment by lnussel** [comment]
I based it on TW, we do want to take the installer changes from there after all

**Comment by jreidinger** [comment]
@lnussel ok, I created branch opensuse_42_2 Can you please create pull request against that target? it is easier then cherry picking all commits. Thanks

**Comment by lslezak** [comment]
I just have created 42.2 branch from master (TW), please reopen your PR against the `openSUSE-42_2` branch.

@jreidinger `opensuse_42_2` does not follow the [branching schema](http://yastgithubio.readthedocs.io/en/latest/maintenance-branches/#maintenance-branch-naming)

**Comment by lslezak** [comment]
OK, the branch has been created correctly, it was only a typo in the comment.

**Pull request closed without merging**
