### PR TITLE
Start Leap 42.3 version.

### PR DESCRIPTION
**Pull request by jberry-suse**
Starting Leap 42.3 version per https://progress.opensuse.org/issues/14918.

### CODE REVIEW

**Comment by lnussel** [comment]
hmm. this needs to be based on 42.2 instead. You also need to adjust the actual xml file, just the spec file is not enough :)

**Comment by jberry-suse** [comment]
I see the `openSUSE-42_3` branch is even with master. Are you indicating that I should branch from `openSUSE-42_2` make the desired version changes and then submit to `openSUSE-42_3` which would in tern be a backwards history change? Some details about what is expected would be handy.

The files to change then are as follows:
- `Rakefile`
- `control/control.openSUSE.xml`
- `package/skelcd-control-openSUSE.spec`

Otherwise, was the version number correct in `.spec` and the `.changes` entry acceptable? I tried to follow the relevant bits from `CONTRIBUTING.md`.

**Comment by jberry-suse** [comment]
Here is a potential diff against the `openSUSE-42_2` branch.

https://github.com/yast/skelcd-control-openSUSE/compare/openSUSE-42_2...jberry-suse:openSUSE-42_2__openSUSE-42_3

**Comment by jberry-suse** [comment]
Also note `YaST:openSUSE:42.2` exists, but `https://build.opensuse.org/project/show/YaST:openSUSE:42.3` does not, nor many of the other URLs.

**Comment by lnussel** [comment]
Jimmy Berry wrote:
> I see the `openSUSE-42_3` branch is even with master. Are you
> indicating that I should branch from `openSUSE-42_2` make the
> desired version changes and then submit to `openSUSE-42_3` which
> would in tern be a backwards history change? Some details about
> what is expected would be handy.

ic. So there are two ways to do it. Either take 42.2 and cherry pick
needed changes from master or use master and replace the tumbleweed
bits with the 42.2 ones, potentially reverting some changes, then
s/42.2/42.3/. Since the 42.3 branch was created based on master I
guess the latter is the way to go now.

> The files to change then are as follows:
> - `Rakefile`
> - `control/control.openSUSE.xml`
> - `package/skelcd-control-openSUSE.spec`
>
> Otherwise, was the version number correct in `.spec` and the
> `.changes` entry acceptable? I tried to follow the relevant bits
> from `CONTRIBUTING.md`.

That's something the yast team has to comment on.

**Comment by lnussel** [comment]
Jimmy Berry wrote:
> Also note `YaST:openSUSE:42.2` exists, but
> `https://build.opensuse.org/project/show/YaST:openSUSE:42.3` does not,
> nor many of the other URLs.

That will be fixed over time. Shouldn't hinder us atm.

**Comment by jreidinger** [comment]
@lnussel Changes in Rakefile looks correct, it will just not work until we also adapt our auto submission tools, but it should not block this change. We just have to not forget it.

Versioning changes look ok, but we need to increase version for TW. In general I have to say I do not like having TW 42.2.99.X and now just increase to 42.3.99.X to be just a small step ahead. What about using 100.X for TW? I think we will never support downgrade from TW to Leap, but other way is still without problem. What do you think?

**Comment by lnussel** [comment]
Josef Reidinger wrote:
> Versioning changes look ok, but we need to increase version for TW. In
> general I have to say I do not like having TW 42.2.99.X and now just
> increase to 42.3.99.X to be just a small step ahead. What about using
> 100.X for TW? I think we will never support downgrade from TW to Leap,
> but other way is still without problem. What do you think?

Use 84.87+git%cd.%h :-) Like e.g. skelcd-openSUSE and several others.

**Comment by jberry-suse** [comment]
I cherry-picked commit and rebased on 42.3 branch (master).

**Comment by lnussel** [comment]
* products_supported_for_upgrade is different in Leap
* KDE must be ordered first as it is the default
* LXDE is not supported in Leap
* disk proposal settings differ

**Comment by jberry-suse** [comment]
Why is 42.3 branched from master then? Shouldn't I just start from 42.2 and make a backwards history pull request or even have someone clear out 42.3 and repush as branch from 42.2. It seems silly for me to try and figure out all the things that can remain when really only the number should change from previous leap.

Thoughts?

**Comment by lnussel** [comment]
Jimmy Berry wrote:
> Why is 42.3 branched from master then? Shouldn't I just start from
> 42.2 and make a backwards history pull request or even have someone
> clear out 42.3 and repush as branch from 42.2. It seems silly for me
> to try and figure out all the things that can remain when really only
> the number should change from previous leap.

Direction doesn't really matter IMO. AFAICS there are other changes
like the subvolumes that need to be merged from master. So either
way you'd have to either forward port Leap changes or backport TW
ones. The trick is to figure out which ones are relevant :-)

**Comment by jberry-suse** [comment]
The decision is simply a reference to having to do a force push in git and may simplify the work if one branch poing is closer to the desired end state than the other.

I took a look at https://github.com/yast/skelcd-control-openSUSE/compare/master...openSUSE-42_2 and did not include a few hunks like

```diff
-                <logon>xdm</logon>
+                <logon></logon>
```

and the diffs tweaking `workflows` as it seems some rearranging was done most likely intentionally. If those need updates some details on what is expect or perhaps some more familiar can make a followup.

**Comment by jreidinger** [comment]
@jberry-suse I will merge this change, but please change target branch for pull request to openSUSE-42_3 ( you can just edit it at top if this pull request )

**Comment by jreidinger** [comment]
I changed it myself, so thanks for your contribution.

**Comment by jreidinger** [comment]
@lnussel I setup jenkins to auto submit this package, but in the end it failed with schema validation. I expect in Leap 42.3 is not yet SP3 packages, right?

**Comment by nilxam** [comment]
yes, SP3 changes does not yet submit to 42.3.

**Comment by lnussel** [comment]
partially. which packages are missing?

**Comment by jreidinger** [comment]
@lnussel it should be already OK, I think

**Pull request merged**
